In [140]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

a9 = np.arange(9).reshape(3, 3)
a12 = np.arange(12).reshape(3, 4)
a20 = np.arange(20).reshape(4, 5)

df9 = DataFrame(a9, index=list('abc'), columns=list('uvw'))
df12 = DataFrame(a12, index=list('abc'), columns=list('uvwx'))
df20 = DataFrame(a20, index=list('abcd'), columns=list('uvwxy'))

s9 = Series(np.arange(9))

In [ ]:
a12 = 

In [4]:
s = Series([1, 2, 4])
s.values, s.index

(array([1, 2, 4], dtype=int64), RangeIndex(start=0, stop=3, step=1))

In [27]:
s = Series([1, 3, 4, 5], index = ['a', 1, True, 1])
s[s > 3]

True    4
1       5
dtype: int64

In [28]:
2 in s

False

In [29]:
'a' in s

True

In [30]:
s = Series({1: 2, 'a': 3})

In [33]:
Series((1, 2))

0    1
1    2
dtype: int64

In [35]:
dic = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
s = Series(dic, index = ['d', 'e', 'a', 1])

In [37]:
pd.isnull(s)

d    False
e     True
a    False
1     True
dtype: bool

In [39]:
s1 = Series(dic)

In [42]:
s + s1

d    8.0
e    NaN
a    2.0
1    NaN
b    NaN
c    NaN
dtype: float64

In [43]:
s.name, s.index.name

(None, None)

In [44]:
s.name = 's'
s.index.name = 'sindex'

In [46]:
s

sindex
d    4.0
e    NaN
a    1.0
1    NaN
Name: s, dtype: float64

In [48]:
s.index = ['a', 'b', 'c', 'd']

In [49]:
s

a    4.0
b    NaN
c    1.0
d    NaN
Name: s, dtype: float64

In [54]:
data = {'col1': [1, 2, 3, 4], 'col2': [10, 11, 12, 13]}
df = DataFrame(data, index=['a', 'b', 'c', 'd'])
df

col1  col2
a     1    10
b     2    11
c     3    12
d     4    13

In [60]:
data = {'c1': np.arange(100), 'c2': np.random.randn(100)}
df = DataFrame(data)
df.head()

c1        c2
0   0  0.897251
1   1  0.323417
2   2  0.519545
3   3  0.468076
4   4  0.398076

In [75]:
data = {'c1': np.arange(10), 'c2': np.random.randn(10)}
df = DataFrame(data, columns=['c1', 'a', 'c2', 'd'])

In [69]:
df.columns = ['d1', 'd2']

In [80]:
dloc = df.loc[2]

In [81]:
dloc.index

Index(['c1', 'a', 'c2', 'd'], dtype='object')

In [87]:
df.a = np.arange(10)
df

c1  a        c2    d
0   0  0  0.544119  NaN
1   1  1 -0.183977  NaN
2   2  2  0.458444  NaN
3   3  3  0.853920  NaN
4   4  4  1.215658  NaN
5   5  5 -0.281169  NaN
6   6  6  0.555893  NaN
7   7  7 -0.595413  NaN
8   8  8  0.026160  NaN
9   9  9  0.577405  NaN

In [89]:
df.d = Series({1: 'a', 3: 's'})
df

c1  a        c2    d
0   0  0  0.544119  NaN
1   1  1 -0.183977    a
2   2  2  0.458444  NaN
3   3  3  0.853920    s
4   4  4  1.215658  NaN
5   5  5 -0.281169  NaN
6   6  6  0.555893  NaN
7   7  7 -0.595413  NaN
8   8  8  0.026160  NaN
9   9  9  0.577405  NaN

In [90]:
df.loc[3] = [2, 3, 4 ,5]
df

c1  a        c2    d
0   0  0  0.544119  NaN
1   1  1 -0.183977    a
2   2  2  0.458444  NaN
3   2  3  4.000000    5
4   4  4  1.215658  NaN
5   5  5 -0.281169  NaN
6   6  6  0.555893  NaN
7   7  7 -0.595413  NaN
8   8  8  0.026160  NaN
9   9  9  0.577405  NaN

In [92]:
df['e'] = np.arange(10, 20)

In [93]:
df

c1  a        c2    d   e
0   0  0  0.544119  NaN  10
1   1  1 -0.183977    a  11
2   2  2  0.458444  NaN  12
3   2  3  4.000000    5  13
4   4  4  1.215658  NaN  14
5   5  5 -0.281169  NaN  15
6   6  6  0.555893  NaN  16
7   7  7 -0.595413  NaN  17
8   8  8  0.026160  NaN  18
9   9  9  0.577405  NaN  19

In [95]:
del df['a']

In [96]:
df

c1        c2    d   e
0   0  0.544119  NaN  10
1   1 -0.183977    a  11
2   2  0.458444  NaN  12
3   2  4.000000    5  13
4   4  1.215658  NaN  14
5   5 -0.281169  NaN  15
6   6  0.555893  NaN  16
7   7 -0.595413  NaN  17
8   8  0.026160  NaN  18
9   9  0.577405  NaN  19

In [97]:
df['n'] = df['c2'] > 0.5

In [98]:
df

c1        c2    d   e      n
0   0  0.544119  NaN  10   True
1   1 -0.183977    a  11  False
2   2  0.458444  NaN  12  False
3   2  4.000000    5  13   True
4   4  1.215658  NaN  14   True
5   5 -0.281169  NaN  15  False
6   6  0.555893  NaN  16   True
7   7 -0.595413  NaN  17  False
8   8  0.026160  NaN  18  False
9   9  0.577405  NaN  19   True

In [99]:
del df['e']

In [103]:
del df['d']

In [108]:
df['c1'][3] = 30
s = df['c1'].copy()
s

C:\Users\xiaoyezi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


0     0
1     1
2     2
3    30
4     4
5     5
6     6
7     7
8     8
9     9
Name: c1, dtype: int32

In [109]:
data = {'c1': {10: 'a', 11: 'b', 12: 'd'}, 'c2': {9: 's', 10: 'd', 11: 'd'}}
df = DataFrame(data)

In [110]:
df

c1   c2
9   NaN    s
10    a    d
11    b    d
12    d  NaN

In [111]:
df.T

9  10 11   12
c1  NaN  a  b    d
c2    s  d  d  NaN

In [115]:
data

{'c1': {10: 'a', 11: 'b', 12: 'd'}, 'c2': {9: 's', 10: 'd', 11: 'd'}}

In [124]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop = {'Nevada': [1, 2, 3], 'Ohio': [2, 3, 4]}
df = DataFrame(pop, index=[2001, 2002, 2003])
# df = DataFrame(data)
df

Nevada  Ohio
2001       1     2
2002       2     3
2003       3     4

In [127]:
df = DataFrame(np.arange(12).reshape(3,4))
df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [126]:
df

0         1         2         3
0 -0.000413  2.011737  1.090984  0.299405
1  0.622316  0.235361 -0.809065  0.514642
2  1.179436 -1.156051 -1.010153 -0.235798

In [129]:
df = DataFrame([np.arange(4), np.arange(4)])

In [130]:
df.values

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [131]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [132]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [134]:
i = pd.Index(np.arange(0, 10, 2))

In [135]:
i

Int64Index([0, 2, 4, 6, 8], dtype='int64')

In [136]:
i.unique()

Int64Index([0, 2, 4, 6, 8], dtype='int64')

In [138]:
i.insert(3, 12)

Int64Index([0, 2, 4, 12, 6, 8], dtype='int64')

In [139]:
i

Int64Index([0, 2, 4, 6, 8], dtype='int64')

In [140]:
s = Series(['a', 'b', 'c'], index= [0, 2 ,4])

In [141]:
s

0    a
2    b
4    c
dtype: object

In [142]:
s.reindex(np.arange(6), method='ffill')

0    a
1    a
2    b
3    b
4    c
5    c
dtype: object

In [143]:
s

0    a
2    b
4    c
dtype: object

In [146]:
df = DataFrame(np.arange(12).reshape(3,4), index= ['a', 'b', 'c'], columns=['c1', 'c2', 'c3', 'c4'])

In [147]:
df

c1  c2  c3  c4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11

In [149]:
df.index = ['a1', 'a2', 'a3']

In [155]:
df.reindex(['c1', 'c4'], axis=1)

c1  c4
a1   0   3
a2   4   7
a3   8  11

In [153]:
df

c1  c2  c3  c4
a1   0   1   2   3
a2   4   5   6   7
a3   8   9  10  11

In [156]:
df.reindex(columns=['n1', 'c1', 'c3'])

n1  c1  c3
a1 NaN   0   2
a2 NaN   4   6
a3 NaN   8  10

In [157]:
s

0    a
2    b
4    c
dtype: object

In [158]:
s = s.reindex(np.arange(10), method='ffill')

In [165]:
df

c1  c2  c3  c4
a1   0   1   2   3
a2   4   5   6   7
a3   8   9  10  11

In [166]:
df.drop('a1')

c1  c2  c3  c4
a2   4   5   6   7
a3   8   9  10  11

In [168]:
df.drop(columns='c1')

c2  c3  c4
a1   1   2   3
a2   5   6   7
a3   9  10  11

In [174]:
df1 = df
df.drop(['c1', 'c3'], axis=1, )

c2  c4
a1   1   3
a2   5   7
a3   9  11

In [176]:
df.drop('c1', axis=1, inplace=True)

In [178]:
df1

c2  c3  c4
a1   1   2   3
a2   5   6   7
a3   9  10  11

In [181]:
s[2:6]

2    b
3    b
4    c
5    c
dtype: object

In [183]:
df1[df1 < 6]

c2   c3   c4
a1  1.0  2.0  3.0
a2  5.0  NaN  NaN
a3  NaN  NaN  NaN

In [184]:
df1[['c2', 'c4']]

c2  c4
a1   1   3
a2   5   7
a3   9  11

In [185]:
df1['c2':'c4']

Empty DataFrame
Columns: [c2, c3, c4]
Index: []

In [186]:
df1

c2  c3  c4
a1   1   2   3
a2   5   6   7
a3   9  10  11

In [194]:
df1['a1':'a2']

c2  c3  c4
a1   1   2   3
a2   5   6   7

In [3]:
df1 = DataFrame(np.arange(12).reshape(3, 4), index= ['a', 'b', 'c'], columns=['c1', 'c2', 'c3', 'c4'])

In [10]:
df1['a':'c']

c1  c2  c3  c4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11

In [14]:
df1['c1'] = 10

In [18]:
df1[['c1', 'c2']] = 11

In [21]:
df1[df1 > 5]

c1  c2    c3    c4
a  11  11   NaN   NaN
b  11  11   6.0   7.0
c  11  11  10.0  11.0

In [27]:
df1.loc[['a', 'b'], 'c1']

a    11
b    11
Name: c1, dtype: int64

In [28]:
df1.loc['a', ['c1', 'c2']]

c1    11
c2    11
Name: a, dtype: int64

In [31]:
df1.iloc[0, 0:1]

c1    11
Name: a, dtype: int64

In [32]:
n = np.arange(12).reshape(3, 4)

In [37]:
n[2]

array([ 8,  9, 10, 11])

In [38]:
df1

c1  c2  c3  c4
a  11  11   2   3
b  11  11   6   7
c  11  11  10  11

In [39]:
df1.loc['a', 'c3']

2

In [41]:
df1.at['a', 'c3']

2

In [43]:
df1.get_value('a', 'c1')

C:\Users\xiaoyezi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.


11

In [48]:
s = Series(np.arange(10), index = pd.Int64Index(np.arange(1, 11)))

In [53]:
s.iloc[1]

1

In [54]:
s.iloc[1:3]

2    1
3    2
dtype: int32

In [55]:
df2 = DataFrame(np.arange(9).reshape(3, 3), index=list('abc'), columns=list('xyz'))

In [56]:
df2

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8

In [57]:
df1.add(df2, fill_value=0)

c1    c2    c3    c4    x    y    z
a  11.0  11.0   2.0   3.0  0.0  1.0  2.0
b  11.0  11.0   6.0   7.0  3.0  4.0  5.0
c  11.0  11.0  10.0  11.0  6.0  7.0  8.0

In [59]:
1/ df2

x         y      z
a       inf  1.000000  0.500
b  0.333333  0.250000  0.200
c  0.166667  0.142857  0.125

In [60]:
df2.rdiv(1)

x         y      z
a       inf  1.000000  0.500
b  0.333333  0.250000  0.200
c  0.166667  0.142857  0.125

In [62]:
df1.mul(df2, fill_value=1)

c1    c2    c3    c4    x    y    z
a  11.0  11.0   2.0   3.0  0.0  1.0  2.0
b  11.0  11.0   6.0   7.0  3.0  4.0  5.0
c  11.0  11.0  10.0  11.0  6.0  7.0  8.0

In [65]:
df1.pow(df2, fill_value=1)

c1    c2    c3    c4    x    y    z
a  11.0  11.0   2.0   3.0  1.0  1.0  1.0
b  11.0  11.0   6.0   7.0  1.0  1.0  1.0
c  11.0  11.0  10.0  11.0  1.0  1.0  1.0

In [68]:
df2.reindex(columns=list('yxza'), fill_value=2)

y  x  z  a
a  1  0  2  2
b  4  3  5  2
c  7  6  8  2

In [78]:
a12 - a12[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [83]:
df9 - df9.iloc[0]

u  v  w
a  0  0  0
b  3  3  3
c  6  6  6

In [87]:
df9.sub(df9['u'], axis='index')

u  v  w
a  0  1  2
b  0  1  2
c  0  1  2

In [90]:
np.log(df9)

C:\Users\xiaoyezi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


u         v         w
a      -inf  0.000000  0.693147
b  1.098612  1.386294  1.609438
c  1.791759  1.945910  2.079442

In [96]:
f = lambda x: x.max() - x.min()
df12.apply(f, axis=0)

u    8
v    8
w    8
x    8
dtype: int64

In [99]:
df12.mean()

u    4.0
v    5.0
w    6.0
x    7.0
dtype: float64

In [105]:
f = lambda x: Series([min(x), max(x), np.mean(x)], index = ['min', 'max', 'mean'])
df12.apply(f)

u    v     w     x
min   0.0  1.0   2.0   3.0
max   8.0  9.0  10.0  11.0
mean  4.0  5.0   6.0   7.0

In [108]:
f = lambda x: '{:02d}'.format(x)
df12.applymap(f)

u   v   w   x
a  00  01  02  03
b  04  05  06  07
c  08  09  10  11

In [109]:
df12['u'].map(f)

a    00
b    04
c    08
Name: u, dtype: object

In [116]:
df12.sort_index()

u  v   w   x
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [125]:
df = DataFrame({'b':[3, 2, 5,4], 'a': [1, 10, 7,3]}, index = list('xcvb'))

In [136]:
df.sort_values('x', axis=1)

a  b
x   1  3
c  10  2
v   7  5
b   3  4

In [149]:
s = pd.Series([7, -5, 7, 4, 2, 0, 4, 7, 7, 7, 7, 7])
s.rank(method='dense')

0     5.0
1     1.0
2     5.0
3     4.0
4     3.0
5     2.0
6     4.0
7     5.0
8     5.0
9     5.0
10    5.0
11    5.0
dtype: float64

In [151]:
s.is_unique

False

In [152]:
s.index.is_unique

True

In [153]:
df12.sum()

u    12
v    15
w    18
x    21
dtype: int64

In [155]:
df12.cumsum()

u   v   w   x
a   0   1   2   3
b   4   6   8  10
c  12  15  18  21

In [156]:
df12.describe()

u    v     w     x
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [161]:
df12.std()

u    4.0
v    4.0
w    4.0
x    4.0
dtype: float64

In [162]:
df12.var()

u    16.0
v    16.0
w    16.0
x    16.0
dtype: float64

In [164]:
df12.cummax()

u  v   w   x
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [166]:
import pandas_datareader.data as web

In [167]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [174]:
price = pd.DataFrame({ticker:data['Adj Close'] for ticker, data in all_data.items()})

In [176]:
volume = pd.DataFrame({ticker:data['Volume'] for ticker, data in all_data.items()})

In [182]:
changes = price.pct_change()

In [184]:
changes['MSFT'].corr(changes['MSFT'])

1.0

In [185]:
changes.MSFT.cov(changes.IBM)

8.685735903137937e-05

In [186]:
changes.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.373085  0.449937  0.457235
IBM   0.373085  1.000000  0.487219  0.404334
MSFT  0.449937  0.487219  1.000000  0.535596
GOOG  0.457235  0.404334  0.535596  1.000000

In [187]:
changes.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000107  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000239

In [188]:
changes.corrwith(changes.IBM)

AAPL    0.373085
IBM     1.000000
MSFT    0.487219
GOOG    0.404334
dtype: float64

In [193]:
s9.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [194]:
s9.value_counts()

8    1
7    1
6    1
5    1
4    1
3    1
2    1
1    1
0    1
dtype: int64

In [204]:
s9.isin([1, 2])

0    False
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [206]:
df9.apply(pd.value_counts).fillna(0)

u    v    w
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0
4  0.0  1.0  0.0
5  0.0  0.0  1.0
6  1.0  0.0  0.0
7  0.0  1.0  0.0
8  0.0  0.0  1.0